### PR TITLE
cargo: set CVE_PRODUCT

### LINKED ISSUE #118: [issue] Investigate cargo build failure in #107
#107 fails to build even though all the change does is set CVE_PRODUCT.

> | error[E0463]: can't find crate for `proc_macro`
|    --> /usr/src/debug/cargo/1.59.0-r0/rustc-1.59.0-src/vendor/proc-macro2-1.0.30/src/lib.rs:102:1
|     |
| 102 | extern crate proc_macro;
|     | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

https://github.com/garmin/meta-lts-collab/actions/runs/27705143395/job/82777058119?pr=107

Investigate and resolve the build failure so #107 can be merged.

### PR DESCRIPTION
**Pull request by colin-pm**
This removes mediawiki:cargo CVEs from CVE metrics.
* CVE-2026-39837, CVE-2026-39839, CVE-2026-39840, CVE-2026-39841

Reference: [https://git.openembedded.org/openembedded-core/commit/?id=a5cb71e7df95925a5c342c341e699e244b1b84f6]

Edit: Also added commit to allow cargo to just build natively to fix CI errors (Fixes #118)

### CODE REVIEW

File: scripts/get-bitbake-targets.py [hunk 1]
```diff
@@ -65,20 +78,45 @@ def get_all_bpns() -> List[str]:
...
 
-def get_bpns(modified_files: Optional[List[Path]] = None) -> List[str]:
+def get_bpns(
+    modified_files: Optional[List[Path]] = None, bpn_filter: BPNFilter = BPNFilter.ALL
+) -> List[str]:
     """Either gets a list of all the BPNs in the layer, or just the BPNs that are associated with modified files.
 
     Args:
         modified_files (Optional[List[Path]], optional): Files that have been modified. Defaults to None.
+        native_only (bool, optional): Whether to only return native-only BPNs. Defaults to False.
```
Comment (JoshuaWatt) [inline scripts/get-bitbake-targets.py]: This doesn't match the function signature

**Review by JoshuaWatt — APPROVED** [review]
