### ISSUE TITLE
[issue] Investigate cargo build failure in #107

### ISSUE THREAD

**Issue by colin-pm** [garmin/meta-lts-collab#118]
#107 fails to build even though all the change does is set CVE_PRODUCT.

> | error[E0463]: can't find crate for `proc_macro`
|    --> /usr/src/debug/cargo/1.59.0-r0/rustc-1.59.0-src/vendor/proc-macro2-1.0.30/src/lib.rs:102:1
|     |
| 102 | extern crate proc_macro;
|     | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

https://github.com/garmin/meta-lts-collab/actions/runs/27705143395/job/82777058119?pr=107

Investigate and resolve the build failure so #107 can be merged.

**Comment by colin-pm** [comment]
I looked at this for a bit on Saturday. I could fix this build error by overriding `${S}` in meta-rust/recipes-devtools/rust/libstd-rs.inc.
```
S = "${RUSTSRC}/src/libtest"
```
https://github.com/meta-rust/meta-rust/issues/266#issuecomment-616767720

See also:
https://github.com/yoctoproject/poky/commit/55dbedbd242221ad1a3fa8aceb6789524193ae1a

This fixed the build error described in this issue, but also caused a whole bunch of compilation errors in cargo. At this point I'm somewhat at a loss on how to easily fix this build error. I'm not sure it's worth fixing all this in meta-lts-collab, so the alternate option I investigated was adding support for building some recipes natively instead of within the test image in CI.

https://github.com/garmin/meta-lts-collab/pull/107/changes/3198999913c2cd58ce4f3b9330a89f73af1e3c53

Cargo builds fine natively, so this will ensure CI tests continue to pass while still providing some basic integrity checking for recipes like cargo.
